<?php

namespace Zenya\Api;

require_once dirname(__FILE__) . '/../../../../../../../../../../../../../www/ENCOURS/zenya-api-server/src/php/Zenya/Api/Resource.php';

/**
 * Test class for Resource.
 * Generated by PHPUnit on 2012-05-14 at 14:49:08.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Resource
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Resource;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Zenya\Api\Resource::getResource
	 * @todo Implement testGetResource().
	 */
	public function testGetResource()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Zenya\Api\Resource::getPublicAppelation
	 * @todo Implement testGetPublicAppelation().
	 */
	public function testGetPublicAppelation()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Zenya\Api\Resource::getInternalAppelation
	 * @todo Implement testGetInternalAppelation().
	 */
	public function testGetInternalAppelation()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Zenya\Api\Resource::getResources
	 * @todo Implement testGetResources().
	 */
	public function testGetResources()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
