<?php
require_once APP_TOPDIR . '/Zenya/Api/Server.php';

use Zenya\Api;

/**
 * Test class for Resource.
 * Generated by PHPUnit on 2012-06-04 at 10:48:49.
 */
class ResourceTest extends \PHPUnit_Framework_TestCase
{

    protected $resource;

    public $resources = array('BlankResource'=>'Zenya\Api\Resource\BlankResource');

    protected function setUp()
    {
        // todo remove this dependency!!!
        $server = new Zenya\Api\Server;
        //echo $server->run();

        $this->resource = new Zenya\Api\Resource($server);
    }

    protected function tearDown()
    {
    }

    /**
     * @covers Zenya\Api\Resource::__construct
     */
    public function testConstructor()
    {
        // TODO: test listeners!
    }

    /**
     * @covers Zenya\Api\Resource::SetRouteOverrides
     */
    public function testSetRouteOverridesOnGet()
    {
        $routes = array(
            '/:controller/:paramUn' => array(),
        );
        $route = new Zenya\Api\Router($routes);
        $route->map('/controller/paramUn');
        $route->setMethod('GET');
        $this->resource->setRouteOverrides($route);
        $this->assertEquals('controller', $route->getController());
    }

    /**
     * @covers Zenya\Api\Resource::SetRouteOverrides
     */
    public function testSetRouteOverridesOnHead()
    {
        $routes = array(
            '/:controller/:paramUn' => array(),
        );
        $route = new Zenya\Api\Router($routes);
        $route->map('/controller/paramUn');
        $route->setMethod('HEAD');
        $this->resource->setRouteOverrides($route);
        $this->assertEquals('HTTP_HEAD', $route->getController());

        $params = $route->params; // TODO: review!
        $this->assertEquals('controller', $params['resource']);
    }

    /**
     * @covers Zenya\Api\Resource::call
     */
    public function testCall()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $this->assertSame( $this->resources, $this->Obj->getResources() );
    }

    /**
     * @covers Zenya\Api\Resource::getMethods
     */
    public function testGetMethods()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}